import { Instrument } from "./types";

export const INSTRUMENTS: Instrument[] = [
  // ============ ACCIONES LOCALES - MERVAL (Líderes) ============
  {
    id: "GGAL",
    name: "Grupo Financiero Galicia",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Principal grupo financiero argentino. Ofrece servicios bancarios, seguros y gestión de activos.",
    priceARS: 8250.50,
    priceUSD: 8.15,
  },
  {
    id: "YPF",
    name: "YPF S.A.",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Empresa líder en energía de Argentina. Exploración, producción y refinación de petróleo y gas.",
  },
  {
    id: "PAMP",
    name: "Pampa Energía",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Empresa integrada de energía. Generación eléctrica, petróleo y gas natural.",
  },
  {
    id: "BMA",
    name: "Banco Macro",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Uno de los bancos privados más grandes de Argentina. Red extensa de sucursales.",
  },
  {
    id: "TRAN",
    name: "Transener",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Empresa de transporte de energía eléctrica de alta tensión en Argentina.",
  },
  {
    id: "EDN",
    name: "Edenor",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Distribuidora de energía eléctrica más grande de Argentina. Zona norte y centro de Buenos Aires.",
  },
  {
    id: "ALUA",
    name: "Aluar Aluminio Argentino",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Principal productor de aluminio primario de Argentina. Exportación y mercado local.",
  },
  {
    id: "TXAR",
    name: "Ternium Argentina",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Productor líder de acero plano en América Latina. Sector industrial y construcción.",
  },
  {
    id: "LOMA",
    name: "Loma Negra",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Líder en producción de cemento y materiales de construcción en Argentina.",
  },
  {
    id: "CEPU",
    name: "Central Puerto",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Generadora de energía eléctrica. Centrales térmicas y energías renovables.",
  },
  {
    id: "COME",
    name: "Sociedad Comercial del Plata",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Empresa diversificada con negocios en petróleo, gas, energía y agronegocios.",
  },
  {
    id: "CRES",
    name: "Cresud",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Empresa agropecuaria con tierras en Argentina, Brasil, Paraguay y Bolivia.",
  },
  {
    id: "TGSU2",
    name: "Transportadora de Gas del Sur",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Transporte de gas natural por gasoductos en el sur y centro de Argentina.",
  },
  {
    id: "MIRG",
    name: "Mirgor",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Fabricación de productos electrónicos, aires acondicionados y celulares en Tierra del Fuego.",
  },
  {
    id: "BYMA",
    name: "Bolsas y Mercados Argentinos",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Operador del mercado de valores de Argentina. Infraestructura del mercado de capitales.",
  },
  {
    id: "BBAR",
    name: "Banco BBVA Argentina",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Banco privado internacional. Servicios financieros retail y corporativos.",
  },
  {
    id: "TGNO4",
    name: "Transportadora de Gas del Norte",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Transporte de gas natural en el norte de Argentina. Infraestructura energética.",
  },
  {
    id: "AGRO",
    name: "Agroindustrial",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Empresa del sector agroindustrial argentino.",
  },
  {
    id: "VALO",
    name: "Banco de Valores",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Entidad financiera especializada en mercado de capitales y servicios de inversión.",
  },
  {
    id: "IRSA",
    name: "IRSA Inversiones y Representaciones",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Empresa líder en real estate. Shopping centers, oficinas y hoteles.",
  },
  {
    id: "SUPV",
    name: "Supervielle",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Grupo financiero con banco, seguros y asset management.",
  },
  {
    id: "CVH",
    name: "Cablevision Holding",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Empresa de telecomunicaciones. Internet, cable y telefonía.",
  },
  {
    id: "METR",
    name: "Metrogas",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Distribuidora de gas natural en la zona metropolitana de Buenos Aires.",
  },
  {
    id: "CGPA2",
    name: "Camuzzi Gas Pampeana",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Distribuidora de gas natural en la región pampeana.",
  },
  {
    id: "HARG",
    name: "Holcim Argentina",
    category: "Acción Local",
    currency: "ARS",
    rateType: "N/A",
    description: "Producción de cemento, hormigón y agregados para construcción.",
  },

  // ============ BONOS SOBERANOS LEY NEW YORK - HARD DOLLAR ============
  {
    id: "GD30",
    name: "Bono Global 2030 USD",
    category: "Bono Soberano Ley NY",
    currency: "USD",
    rateType: "Hard Dollar",
    description: "Bono soberano en dólares con vencimiento 2030. Legislación Nueva York. Mayor seguridad jurídica.",
    priceARS: 51234.00,
    priceUSD: 50.62,
    yieldUSD: 18.45,
  },
  {
    id: "GD35",
    name: "Bono Global 2035 USD",
    category: "Bono Soberano Ley NY",
    currency: "USD",
    rateType: "Hard Dollar",
    description: "Bono soberano en dólares con vencimiento 2035. Legislación Nueva York.",
    priceARS: 47890.00,
    priceUSD: 47.32,
    yieldUSD: 19.87,
  },
  {
    id: "GD38",
    name: "Bono Global 2038 USD",
    category: "Bono Soberano Ley NY",
    currency: "USD",
    rateType: "Hard Dollar",
    description: "Bono soberano en dólares con vencimiento 2038. Legislación Nueva York.",
  },
  {
    id: "GD41",
    name: "Bono Global 2041 USD",
    category: "Bono Soberano Ley NY",
    currency: "USD",
    rateType: "Hard Dollar",
    description: "Bono soberano en dólares con vencimiento 2041. Legislación Nueva York.",
  },
  {
    id: "GD46",
    name: "Bono Global 2046 USD",
    category: "Bono Soberano Ley NY",
    currency: "USD",
    rateType: "Hard Dollar",
    description: "Bono soberano en dólares con vencimiento 2046. Legislación Nueva York. Largo plazo.",
  },

  // ============ BONOS SOBERANOS LEY ARGENTINA - HARD DOLLAR ============
  {
    id: "AL30",
    name: "Bono Argentina 2030 USD",
    category: "Bono Soberano Ley AR",
    currency: "USD",
    rateType: "Hard Dollar",
    description: "Bono soberano en dólares con vencimiento 2030. Legislación Argentina. Mayor liquidez local.",
    priceARS: 49875.00,
    priceUSD: 49.28,
    yieldUSD: 19.24,
  },
  {
    id: "AL35",
    name: "Bono Argentina 2035 USD",
    category: "Bono Soberano Ley AR",
    currency: "USD",
    rateType: "Hard Dollar",
    description: "Bono soberano en dólares con vencimiento 2035. Legislación Argentina.",
    priceARS: 46120.00,
    priceUSD: 45.56,
    yieldUSD: 20.65,
  },
  {
    id: "AL41",
    name: "Bono Argentina 2041 USD",
    category: "Bono Soberano Ley AR",
    currency: "USD",
    rateType: "Hard Dollar",
    description: "Bono soberano en dólares con vencimiento 2041. Legislación Argentina.",
  },
  {
    id: "AE38",
    name: "Bono Argentina 2038 EUR",
    category: "Bono Soberano Ley AR",
    currency: "EUR",
    rateType: "Hard Dollar",
    description: "Bono soberano en euros con vencimiento 2038. Legislación Argentina.",
  },

  // ============ BONOS SOBERANOS LEY ARGENTINA - DOLLAR LINK ============
  {
    id: "TZVD5",
    name: "Bono Dollar Linked Dic 2025",
    category: "Bono Soberano Ley AR",
    currency: "ARS",
    rateType: "Dollar Link",
    description: "Bono del Tesoro vinculado al dólar con vencimiento diciembre 2025. Cobertura cambiaria.",
  },
  {
    id: "TZX26",
    name: "Bono Dollar Linked 2026",
    category: "Bono Soberano Ley AR",
    currency: "ARS",
    rateType: "Dollar Link",
    description: "Bono del Tesoro vinculado al dólar. Ajuste por tipo de cambio oficial.",
  },
  {
    id: "DICP",
    name: "Bono Dollar Linked Largo Plazo",
    category: "Bono Soberano Ley AR",
    currency: "ARS",
    rateType: "Dollar Link",
    description: "Bono del Tesoro vinculado al dólar de más largo plazo.",
  },

  // ============ BONOS SOBERANOS LEY ARGENTINA - CER ============
  {
    id: "TZXD5",
    name: "Bono CER Dic 2025",
    category: "Bono Soberano Ley AR",
    currency: "ARS",
    rateType: "CER",
    description: "Bono del Tesoro ajustado por CER con vencimiento diciembre 2025. Protección contra inflación.",
    priceARS: 98500.00,
    yieldARS: 8.75,
  },
  {
    id: "TX26",
    name: "Bono CER 2026",
    category: "Bono Soberano Ley AR",
    currency: "ARS",
    rateType: "CER",
    description: "Bono del Tesoro en pesos ajustado por CER. Cobertura inflacionaria.",
    priceARS: 102300.00,
    yieldARS: 9.25,
  },
  {
    id: "TX28",
    name: "Bono CER 2028",
    category: "Bono Soberano Ley AR",
    currency: "ARS",
    rateType: "CER",
    description: "Bono del Tesoro en pesos ajustado por CER con vencimiento 2028.",
  },

  // ============ BONOS DUALES ============
  {
    id: "BOTE",
    name: "Bono Dual Mar 2026",
    category: "Bono Soberano Ley AR",
    currency: "ARS",
    rateType: "Dual",
    description: "Bono dual: paga la mayor entre tasa fija 2.25% mensual o tasa variable. Vto marzo 2026.",
  },
  {
    id: "BOGAR",
    name: "Bono Dual Jun 2026",
    category: "Bono Soberano Ley AR",
    currency: "ARS",
    rateType: "Dual",
    description: "Bono dual: paga la mayor entre tasa fija 2.19% mensual o tasa variable. Vto junio 2026.",
  },

  // ============ LETRAS DEL TESORO (LECAP - Tasa Fija) ============
  {
    id: "S31O5",
    name: "LECAP Oct 2025",
    category: "Letra del Tesoro",
    currency: "ARS",
    rateType: "Tasa Fija",
    description: "Letra capitalizable en pesos con vencimiento octubre 2025. Corto plazo.",
  },
  {
    id: "S31L5",
    name: "LECAP Jul 2025",
    category: "Letra del Tesoro",
    currency: "ARS",
    rateType: "Tasa Fija",
    description: "Letra capitalizable en pesos con vencimiento julio 2025. Corto plazo.",
  },
  {
    id: "S28N5",
    name: "LECAP Nov 2025",
    category: "Letra del Tesoro",
    currency: "ARS",
    rateType: "Tasa Fija",
    description: "Letra capitalizable en pesos con vencimiento noviembre 2025. Corto plazo.",
  },

  // ============ OBLIGACIONES NEGOCIABLES - HARD DOLLAR ============
  {
    id: "YCA9O",
    name: "ON YPF Clase XXXIV 2034",
    category: "Obligación Negociable",
    currency: "USD",
    rateType: "Hard Dollar",
    description: "Obligación negociable de YPF en dólares. Tasa fija, vencimiento 2034. Rating AAA(arg).",
  },
  {
    id: "PAMO7",
    name: "ON Pampa Energía 2027",
    category: "Obligación Negociable",
    currency: "USD",
    rateType: "Hard Dollar",
    description: "Obligación negociable de Pampa Energía. Sector energético.",
  },
  {
    id: "TXRO9",
    name: "ON Ternium 2029",
    category: "Obligación Negociable",
    currency: "USD",
    rateType: "Hard Dollar",
    description: "Obligación negociable de Ternium Argentina. Sector industrial siderúrgico.",
  },
  {
    id: "IRO1",
    name: "ON IRSA Clase XXIV",
    category: "Obligación Negociable",
    currency: "USD",
    rateType: "Hard Dollar",
    description: "Obligación negociable de IRSA. Sector inmobiliario.",
  },
  {
    id: "TGO9",
    name: "ON Transportadora de Gas del Sur",
    category: "Obligación Negociable",
    currency: "USD",
    rateType: "Hard Dollar",
    description: "Obligación negociable de TGS. Infraestructura de gas.",
  },
  {
    id: "TECO2",
    name: "ON Telecom Argentina 2031",
    category: "Obligación Negociable",
    currency: "USD",
    rateType: "Hard Dollar",
    description: "Obligación negociable de Telecom. Sector telecomunicaciones.",
  },
  {
    id: "GNO7",
    name: "ON Genneia 2027",
    category: "Obligación Negociable",
    currency: "USD",
    rateType: "Hard Dollar",
    description: "Obligación negociable de Genneia. Energías renovables.",
  },
  {
    id: "PAEO5",
    name: "ON Pan American Energy 2025",
    category: "Obligación Negociable",
    currency: "USD",
    rateType: "Hard Dollar",
    description: "Obligación negociable de Pan American Energy. Petróleo y gas.",
  },

  // ============ CEDEARS (Acciones extranjeras) ============
  {
    id: "AAPL",
    name: "Apple Inc.",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "Certificado de depósito argentino de Apple. Tecnología estadounidense.",
    priceARS: 28500.00,
    priceUSD: 28.16,
  },
  {
    id: "MSFT",
    name: "Microsoft",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "Certificado de depósito argentino de Microsoft. Software y cloud computing.",
    priceARS: 45200.00,
    priceUSD: 44.67,
  },
  {
    id: "GOOGL",
    name: "Alphabet (Google)",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "Certificado de depósito argentino de Alphabet/Google. Tecnología e internet.",
  },
  {
    id: "TSLA",
    name: "Tesla",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "Certificado de depósito argentino de Tesla. Vehículos eléctricos.",
  },
  {
    id: "AMZN",
    name: "Amazon",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "Certificado de depósito argentino de Amazon. E-commerce y cloud.",
  },
  {
    id: "META",
    name: "Meta (Facebook)",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "Certificado de depósito argentino de Meta Platforms. Redes sociales.",
  },
  {
    id: "NVDA",
    name: "NVIDIA",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "Certificado de depósito argentino de NVIDIA. GPUs e inteligencia artificial.",
  },
  {
    id: "KO",
    name: "Coca-Cola",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "Certificado de depósito argentino de Coca-Cola. Bebidas.",
  },
  {
    id: "WMT",
    name: "Walmart",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "Certificado de depósito argentino de Walmart. Retail estadounidense.",
  },
  {
    id: "DIS",
    name: "Disney",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "Certificado de depósito argentino de Disney. Entretenimiento.",
  },
  {
    id: "MELI",
    name: "MercadoLibre",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "Certificado de depósito argentino de MercadoLibre. E-commerce latinoamericano.",
  },
  {
    id: "BABA",
    name: "Alibaba",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "Certificado de depósito argentino de Alibaba. E-commerce chino.",
  },
  {
    id: "GOLD",
    name: "Barrick Gold",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "Certificado de depósito argentino de Barrick Gold. Minería de oro.",
  },
  {
    id: "SPY.C",
    name: "SPY (S&P 500 ETF)",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "ETF que replica el índice S&P 500. Exposición a 500 empresas estadounidenses.",
  },
  {
    id: "QQQ.C",
    name: "QQQ (Nasdaq-100 ETF)",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "ETF que replica el Nasdaq-100. Exposición a tecnología estadounidense.",
  },
  {
    id: "EEM.C",
    name: "EEM (Emerging Markets ETF)",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "ETF de mercados emergentes. Diversificación internacional.",
  },
  {
    id: "GLD.C",
    name: "GLD (Gold ETF)",
    category: "CEDEAR",
    currency: "USD",
    rateType: "N/A",
    description: "ETF que replica el precio del oro. Cobertura y refugio de valor.",
  },

  // ============ EFECTIVO ============
  {
    id: "CASH",
    name: "Efectivo Pesos",
    category: "Efectivo",
    currency: "ARS",
    rateType: "N/A",
    description: "Posición en efectivo en pesos argentinos. Liquidez inmediata.",
  },
  {
    id: "USDC",
    name: "Dólares USD",
    category: "Efectivo",
    currency: "USD",
    rateType: "N/A",
    description: "Posición en dólares estadounidenses. Cobertura cambiaria.",
  },
];
